baseURL         = "https://myblog-9mp.pages.dev"
languageCode    = "zh-hant-tw"
title           = "Life with everything"
theme           = "hugo-theme-stack" # 加入這行，指定讀取本地 themes 資料夾
paginate        = 15
enableGitInfo   = true

defaultContentLanguage = "zh-hant-tw"
hasCJKLanguage         = true # 你的遊記會用到中文，這行很重要

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    copyright = "Hazwle's Blog"
    customSCSS = ["scss/custom.scss"]

    [params.header]
        title = "Life with everything"  # 這裡會決定標籤頁顯示的文字
        
[params.comments]
    enabled = true
    provider = "giscus"

[params.comments.giscus]
    repo = "tigoodday0928-bot/MyBlog-comments"
    repoID = "R_kgDOSaAinA"
    category = "General"
    categoryID = "DIC_kwDOSaAinM4C8ww3"
    mapping = "title"
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "bottom"
    lang = "zh-TW"

# 定義側邊欄分類選單
[[menu.sidebar_categories]]
    name = "遊玩景點"
    identifier = "travel" # 父節點的唯一識別碼
    url = "/categories/遊玩景點/"
    weight = 1

[[menu.sidebar_categories]]
    name = "台灣"
    parent = "travel" # 指向上面的 identifier，就會變成子目錄
    url = "/categories/台灣/"
    weight = 1

[[menu.sidebar_categories]]
    name = "泰國曼谷"
    parent = "travel" 
    url = "/categories/泰國曼谷/"
    weight = 2

[[menu.sidebar_categories]]
    name = "日本東京"
    parent = "travel"
    url = "/categories/日本東京/"
    weight = 3

[[menu.sidebar_categories]]
    name = "中國上海"
    parent = "travel"
    url = "/categories/中國上海/"
    weight = 4

[[menu.sidebar_categories]]
    name = "美食紀錄"
    identifier = "food"        # 父層的 identifier
    url = "/categories/美食紀錄/"
    weight = 2

[[menu.sidebar_categories]]
    name = "台灣美食"
    parent = "food"            # 指向父層的 identifier
    url = "/categories/台灣美食/"
    weight = 1

[[menu.sidebar_categories]]
    name = "泰國曼谷美食"
    parent = "food"            
    url = "/categories/泰國曼谷美食/"
    weight = 2

# 如果還有其他子分類繼續加：
[[menu.sidebar_categories]]
    name = "日本東京美食"
    parent = "food"
    url = "/categories/日本東京美食/"
    weight = 3

[[menu.sidebar_categories]]
    name = "中國上海美食"
    parent = "food"
    url = "/categories/中國上海美食/"
    weight = 4

[[menu.sidebar_categories]]
    name = "自創內容"
    identifier = "creative"
    url = "/categories/自創內容/"
    weight = 3

[[menu.sidebar_categories]]
    name = "影劇心得"
    parent = "creative"
    url = "/categories/影劇心得/"
    weight = 1

[[menu.sidebar_categories]]
    name = "電玩精華"
    identifier = "gaming"
    url = "/categories/電玩精華/"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  